### PR TITLE
Fix #16: Add explanation about the random string used as a pepper for argon2

### LINKED ISSUE #16: Argon2 salt "looks dangerous"
Preface: I do not intend to attack you and am actually likely to start using this; but one thing seems odd to me who has a cryptography and security background.

https://github.com/paulgreg/UniquePasswordBuilder/blob/67fc98394e6c7ce33bb4b3e87512e1b213bec632/src/passwordgeneration.js#L76

I know, the comment above it says it is randomly generated. But why is it there in the first place? What extra security does it bring beyond the master password? Can you _prove_ that it was random?

Asking, as it simply _looks_ bad. Like, if I wanted to make a trojaned password generator in C, I would probably hide some payload in a string like this and inject my bad behavior that way. How would it be involved? By a buffer overflow in the argon2 implementation of course. And of course I would claim that my exploit payload is just random data used as a salt...

Yes, I know exploits in JavaScript do not work this way. This approach works better in native apps. I do not know whether WebAssembly makes buffer overflow exploits possible though.

Or remember the Dual_EC_DRBG debacle? That was also caused by a "random looking" number... "what if there is a vulnerability in Argon2 triggered by this specific string in th salt, causing a backdoor?"

The common solution to this cryptographers use to cast away doubts like this when a parameter is needed but its value does not matter is using a "nothing up my sleeves" number. You know, something like 0x31415926535... (digits of pi) or similar.

Of course doing that would break existing generated passwords. But I would simply like to know:

- Can this value be freely changed to whatever I like when I host my own instance? From what I know about Argon2, yes.
- If it can, would it maybe be nice to have an option in the bookmarklet/app/settings to change this salt to another value (basically a second half of a master password)?
- If not, can you document explicitly in the source that changing this value is fine as long as one accepts breaking generated passwords? That probably would also cast away some doubt there. And maybe explicitly recommend changing this when making your own deployment, to use it as "per organization salt"...

Thank you!

### PR DESCRIPTION
**Pull request by paulgreg**

### CODE REVIEW

File: src/passwordgeneration.js [hunk 1]
```diff
@@ -1,5 +1,11 @@
 (function(upb) {
 
+    // That constant is concatenated to the current domain, the password and the user salt before applying the argon2 algorithm.
```
Comment (pmiossec) [inline src/passwordgeneration.js]: The password is not in the salt.

File: src/passwordgeneration.js [hunk 2]
```diff
@@ -73,7 +79,7 @@
         } else {
             var difficulty = algoParams.difficulty || 10;
             //Good long salt generated with http://passwordsgenerator.net/
```
Comment (pmiossec) [inline src/passwordgeneration.js]: You could either delete this line or move it next to the string...

**Comment by pmiossec** [comment]
Except the 2 small changes, seems good!
